version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g serverless
      - npm install -g serverless-python-requirements
  build:
    commands:
      - echo Build started on `date`
      - sls deploy
  post_build:
     commands:
      - echo Build completed on `date`
